version: '3'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: redhat123
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: redhat123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: redhat123
    ports:
      - '9494:8080'
    depends_on:
      - postgres
